#!/bin/sh
bspc rule -r "*"

#
# autostart applications
#

xrandr --output DP-0 --primary --right-of DP-3

sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

$HOME/.scripts/polybar/launch.sh &

$HOME/.scripts/bspwm/cleanfullscreen &

$HOME/.scripts/bspwm/edge_switcher &

picom -b &

nitrogen --restore &

dunst &

xrdb -merge $HOME/.Xresources
xrdb -merge $HOME/.Xresources.d/*

killall urxvtd
urxvtd -q &

killall xautolock
$HOME/.scripts/bspwm/autolocker &

pipewire &

killall -9 conky
/usr/bin/conky -q -c $HOME/.config/conky/conkyrc &

blueman-applet &

killall volumeicon
volumeicon &

killall nm-applet
nm-applet &

killall barrier
barrier &

killall pcmanfm-qt
pcmanfm-qt --dekstop-off &

xsetroot -cursor_name left_ptr

#
# bspwm configuration
#

# primary
bspc monitor DP-0 -d 6 7 8 9 0
# secondary
bspc monitor DP-3 -d 1 2 3 4 5

bspc config top_padding           35
bspc config bottom_padding        0
bspc config border_width          2
bspc config window_gap            5

bspc config pointer_modifier      lock
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false
bspc config click_to_focus        button1

#
# bspwm rules
#

bspc rule -a URxvt:urxvt_keys_help state=floating

bspc rule -a Blueman-manager state=floating
bspc rule -a Chromium desktop='^2'
bspc rule -a feh state=fullscreen
bspc rule -a Gimp-2.8 state=floating
bspc rule -a Gnome-calendar state=floating center=true
bspc rule -a Gnome-control-center state=floating center=true
bspc rule -a Gnome-tweaks state=floating center=true
bspc rule -a Google-chrome desktop=^1 follow=true
bspc rule -a mplayer2 state=floating
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Screenkey manage=off
bspc rule -a Terminator:Preferences state=floating
