#! /bin/sh


#
# autostart applications
#
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

$HOME/.scripts/polybar/launch.sh &

picom &

feh --bg-fill $HOME/.config/wall.png &

dunst &

xrdb $HOME/.Xresources
xrdb $HOME/.Xresources.d/*

$HOME/.scripts/bspwm/autolocker &

killall conky
/usr/bin/conky -q -c ~/.config/conky/conkyrc &

blueman-applet &

killall volumeicon
volumeicon &

nm-applet &


#
# bspc configuration
#

# primary
bspc monitor DP-0 -d 6 7 8 9 0
# secondary
bspc monitor DP-3 -d 1 2 3 4 5

bspc config top_padding          0
bspc config bottom_padding       20
bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio            0.52
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer  false
bspc config click_to_focus         true


bspc rule -a URxvt:urxvt_keys_help state=floating

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Terminator:Preferences state=floating
bspc rule -a Gnome-tweaks state=floating center=true
bspc rule -a Google-chrome desktop=^1 follow=true
bspc rule -a Gimp-2.8 state=floating
bspc rule -a Blueman-manager state=floating
