#!/bin/sh
bspc rule -r "*"

#
# Initial Configuration
#

# Call an xrandr config script to arrange monitors.
# Example contents:
#   xrandr --output DP-0 --primary --right-of DP-3
#   -or-
#   xrandr --ouput eDP-1 --primary --left-of HDMI-1
if [ -f "$HOME/.config/xrandr/xrandrrc" ]; then
  source $HOME/.config/xrandr/xrandrrc
fi

killall clean-full-screen
$HOME/.scripts/bspwm/clean-full-screen &

# Only load edge-switcher if there is one monitor
if [ "$(xrandr --listmonitors | head -1 | cut -d " " -f 2)" -eq "1" ]; then
  killall edge-switcher
  $HOME/.scripts/bspwm/edge-switcher &
fi

xsetroot -cursor_name left_ptr &

# font config
xset +fp /usr/share/fonts &
xset +fp ~/.fonts &
xset fp rehash &
fc-cache -f &

# screensaver options
xset s off &
xset s noblank &
xset s noexpose &

#
# Autostart Applications
#

killall sxhkd
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

$HOME/.scripts/polybar/launch.sh &

picom -b &

nitrogen --restore &

dunst &

xrdb -merge $HOME/.Xresources &

killall urxvtd
urxvtd -q &

killall xautolock
$HOME/.scripts/bspwm/autolocker &

pipewire &

killall -9 conky
/usr/bin/conky -q -c $HOME/.config/conky/conkyrc &

blueman-applet &

killall volumeicon
volumeicon &

killall nm-applet
nm-applet &

killall barrier
barrier &

killall pcmanfm-qt
pcmanfm-qt --dekstop-off &

#
# bspwm configuration
#

# configure desktop tags
$HOME/.scripts/bspwm/dynamic-bspc-monitor

bspc config top_padding           35
bspc config bottom_padding        0
bspc config border_width          2
bspc config window_gap            5

bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner

bspc config automatic_scheme      alternate
bspc config split_ratio           0.50

bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focus_follows_pointer false
bspc config click_to_focus        button1

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

## base theme
#bspc config normal_border_color "#1b1b1b"
#bspc config active_border_color "#1b1b1b"
#bspc config focused_border_color "#aaaaaa"

## highlighted theme
bspc config normal_border_color "#aaaaaa"
bspc config active_border_color "#065738"
bspc config focused_border_color "#a80301"

#
# bspwm rules
#

bspc rule -a *:*:rofiman state=floating
bspc rule -a *:*:sxhkd_key_bindings state=floating
bspc rule -a *:*:polybar-float state=floating

bspc rule -a Blueman-manager state=floating
bspc rule -a Chromium follow=true
bspc rule -a Sxiv state=floating
bspc rule -a Gnome-calendar state=floating center=true
bspc rule -a Gnome-control-center state=floating center=true
bspc rule -a Gnome-tweaks state=floating center=true
bspc rule -a Google-chrome follow=true
bspc rule -a mplayer2 state=floating
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Screenkey manage=off
bspc rule -a Terminator:Preferences state=floating
