#!/bin/sh
#
# ~/.config/X11/xinitrc
#
# Executed by startx (run your window manager from here)

# Set default to gnome if WM env var is unset
session=${2:-"${WM:-gnome}"}

case $session in
  gnome         ) exec dbus-launch --sh-syntax --exit-with-session gnome-session;;
  bspwm         ) exec dbus-launch --sh-syntax --exit-with-session bspwm;;
  gnome-bspwm   ) exec dbus-launch --sh-syntax --exit-with-session gnome-session-bspwm;;
  qtile         ) exec dbus-launch --sh-syntax --exit-with-session qtile;;
  openbox       ) exec dbus-launch --sh-syntax --exit-with-session openbox-session;;
  # No known session, try to run it as command
  *             ) exec dbus-launch --sh-syntax --exit-with-session $session;;
esac
