#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# Here Bspwm is kept as default
session=${2:-"bspwm"}

#-- ensure XDG_Runtime_dir is set
if [ ! -d /run/user/$(id -u) ]; then
  mkdir /run/user/$(id -u)
fi
unset XDG_RUNTIME_DIR
export XDG_RUNTIME_DIR=/run/user/$(id -u)

case $session in
  gnome         ) exec dbus-launch --sh-syntax --exit-with-session gnome-session;;
  bspwm         ) exec dbus-launch --sh-syntax --exit-with-session bspwm;;
  gnome-bspwm   ) exec dbus-launch --sh-syntax --exit-with-session gnome-session-bspwm;;
  qtile         ) exec dbus-launch --sh-syntax --exit-with-session qtile;;
  openbox       ) exec dbus-launch --sh-syntax --exit-with-session openbox-session;;
  # No known session, try to run it as command
  *             ) exec dbus-launch --sh-syntax --exit-with-session $session;;
esac
