#!/bin/sh
#
# ~/.config/X11/xinitrc
#
# Executed by startx (run your window manager from here)

# Set default to gnome if WM env var is unset
session=${1:-"${WM:-gnome}"}
# set launch command
launcher="exec dbus-launch --sh-syntax --exit-with-session"

case $session in
  gnome         ) $(launcher) gnome-session;;
  kde           ) $(launcher) startplasma-x11;;
  kde-wayland   ) $(launcher) startplasma-wayland;;
  bspwm         ) $(launcher) bspwm;;
  gnome-bspwm   ) $(launcher) gnome-session-bspwm;;
  qtile         ) $(launcher) qtile;;
  openbox       ) $(launcher) openbox-session;;
  # No known session, try to run it as command
  *             ) $(launcher) $session;;
esac
